# This is a basic workflow to help you get started with Actions

name: gatsby deploy

# Controls when the workflow will run
on:
  # main 브랜치에 push 할 때마다 실행
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    name: deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # uses는 이미 만들어진 액션을 사용하는 것
      - name: checkout code
        uses: actions/checkout@v2

      # run은 cmd에서 실행시킬 명령어
      - name: packages install
        run: yarn install
        
      - name: gatsby build
        run: yarn build
        env:
          GH_API_KEY: ${{ secrets.DEPLOY_KEY }}
      
      - name: deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.DEPLOY_KEY }}
          BUILD_DIR: 'public/'
